// <auto-generated />
using System;
using Ensek.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ensek.Data.Migrations
{
    [DbContext(typeof(EnsekDbContext))]
    partial class EnsekDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ensek.Data.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountId = 1234,
                            Firstname = "Freya",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 1239,
                            Firstname = "Noddy",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 1240,
                            Firstname = "Archie",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 1241,
                            Firstname = "Lara",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 1242,
                            Firstname = "Tim",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 1243,
                            Firstname = "Graham",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 1244,
                            Firstname = "Tony",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 1245,
                            Firstname = "Neville",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 1246,
                            Firstname = "Jo",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 1247,
                            Firstname = "Jim",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 1248,
                            Firstname = "Pam",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 2233,
                            Firstname = "Barry",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 2344,
                            Firstname = "Tommy",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 2345,
                            Firstname = "Jerry",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 2346,
                            Firstname = "Ollie",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 2347,
                            Firstname = "Tara",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 2348,
                            Firstname = "Tammy",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 2349,
                            Firstname = "Simon",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 2350,
                            Firstname = "Colin",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 2351,
                            Firstname = "Gladys",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 2352,
                            Firstname = "Greg",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 2353,
                            Firstname = "Tony",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 2355,
                            Firstname = "Arthur",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 2356,
                            Firstname = "Craig",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 4534,
                            Firstname = "JOSH",
                            Lastname = "TEST"
                        },
                        new
                        {
                            AccountId = 6776,
                            Firstname = "Laura",
                            Lastname = "Test"
                        },
                        new
                        {
                            AccountId = 8766,
                            Firstname = "Sally",
                            Lastname = "Test"
                        });
                });

            modelBuilder.Entity("Ensek.Data.Entities.MeterReading", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReadValue")
                        .HasColumnType("int");

                    b.HasKey("AccountId", "ReadDate");

                    b.ToTable("MeterReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
